name: Auto-close external PRs
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  close:
    # Only run for external folks (not OWNER/MEMBER/COLLABORATOR)
    if: ${{ !contains(fromJson('["OWNER","MEMBER","COLLABORATOR"]'), github.event.pull_request.author_association) }}
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: >
            Thanks for the PR! This repository does not accept external contributions.